services:
  - type: web
    name: windows-install-flow
    env: node
    branch: master
    buildCommand: pnpm install && pnpm run build
    # O comando de start pode ser simplificado, pois o Render cuidará do rewrite
    startCommand: npx serve client/dist -l 3000 # -l para especificar a porta, -s para SPA fallback
    plan: free
    autoDeploy: true
    publish: client/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html