# render.yaml
services:
  - type: web
    name: windows-install-flow
    env: node
    branch: main
    buildCommand: pnpm install && pnpm run build
    startCommand: npx serve client/dist -s
    plan: free
    autoDeploy: true
    publish: client/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render usa essa variável internamente